package com.goltd.agrigoussd.helpers.enums;

public enum Question {
    // Registration questions
    REGISTRATION_START,
    REGISTRATION_ENTER_FULL_NAME,
    REGISTRATION_ENTER_AGE,
    REGISTRATION_SELECT_GENDER,
    REGISTRATION_SELECT_LOCATION_PROVINCE,
    REGISTRATION_SELECT_LOCATION_DISTRICT,
    REGISTRATION_SELECT_LOCATION_SECTOR,
    REGISTRATION_SELECT_LOCATION_CELL,
    REGISTRATION_SELECT_LOCATION_VILLAGE,
    REGISTRATION_ENTER_PIN,
    REGISTRATION_VERIFY_PIN,
    REGISTRATION_COMPLETED,

    // Main questions
    MAIN_LOGIN,
    MAIN_MENU,
    MAIN_ENTER_PIN,
    MAIN_SELECT_SERVICE,
    MAIN_MENU_ASSOCIATIONS,
    MAIN_MENU_LAND_MANAGEMENT,
    MAIN_MENU_ACTIVITY_RECORDING,
    MAIN_MENU_MINI_REPORT,
    MAIN_MENU_MARKETPLACE,
    MAIN_MENU_BUY_AIRTIME,
    MAIN_MENU_MY_ACCOUNT,
    MAIN_MENU_HELP,

    // Association
    ASSOCIATION_MANAGEMENT,
    ASSOCIATIONS_ENTER_ASSOCIATION_CODE,
    ASSOCIATIONS_SHOW_JOINED_ASSOCIATION,
    ASSOCIATIONS_SHOW_MY_ASSOCIATIONS,
    ASSOCIATIONS_LEAVE_ASSOCIATION,
    ASSOCIATIONS_CONFIRM_LEAVE_ASSOCIATION,
    ASSOCIATION_MANAGEMENT_JOIN,
    ASSOCIATION_MANAGEMENT_LEAVE,
    ASSOCIATION_MANAGEMENT_VIEW,

    // Land management
    LAND_MANAGEMENT,
    LAND_REGISTER_PLOT,
    LAND_PLOT_SIZE,
    LAND_PLOT_UPI,
    LAND_LOCATION_PROVINCE,
    LAND_LOCATION_DISTRICT,
    LAND_LOCATION_SECTOR,
    LAND_LOCATION_CELL,
    LAND_LOCATION_VILLAGE,
    LAND_CONFIRM_MESSAGE,
    LAND_VIEW_PLOTS,
    LAND_CROP_ALLOCATION,
    LAND_CROP_SELECT_PLOT,
    LAND_CROP_REGISTRATION,
    LAND_CROP_TYPE_OF_CROP,
    LAND_CROP_NAME_OF_CROP,
    LAND_CROP_SEED,
    LAND_CROP_CONFIRM_MESSAGE,

    // Activity recording
    ACTIVITY_SHOW_CATEGORY,
    ACTIVITY_SHOW_LIST,
    ACTIVITY_QUANTITY,
    ACTIVITY_COST_PER_UNIT,
    ACTIVITY_CONFIRM_MESSAGE,

    // Mini- report
    REPORT_MANAGEMENT,
    REPORT_SUMMARY_OF_COST,
    REPORT_LAST_RECORDED_ACTIVITY,
    REPORT_PREDICTED_HARVEST,

    // Marketplace

    MARKETPLACE_LIST_PRODUCT,
    MARKETPLACE_PRODUCT_TYPE,
    MARKETPLACE_PRODUCT_NAME,
    MARKETPLACE_PRODUCT_QUANTITY,
    MARKETPLACE_CONFIRM_MESSAGE,

    // Airtime
    AIRTIME_BUYER_TYPE,
    AIRTIME_AMOUNT,
    AIRTIME_CONFIRM_MESSAGE,

    // Account
    ACCOUNT_RESET_PIN,
    ACCOUNT_CURRENT_PIN,
    ACCOUNT_NEW_PIN,
    ACCOUNT_REPEAT_NEW_PIN,
    ACCOUNT_CONFIRM_MESSAGE,

    // Help
    HELP_CONTACT_DETAILS
}
