package com.goltd.agrigoussd.helpers.enums;

public enum Question {
    // Registration questions
    REGISTRATION_ENTER_FULL_NAME,
    REGISTRATION_ENTER_AGE,
    REGISTRATION_SELECT_GENDER,
    REGISTRATION_SELECT_LOCATION_PROVINCE,
    REGISTRATION_SELECT_LOCATION_DISTRICT,
    REGISTRATION_SELECT_LOCATION_SECTOR,
    REGISTRATION_SELECT_LOCATION_CELL,
    REGISTRATION_SELECT_LOCATION_VILLAGE,
    REGISTRATION_ENTER_PIN,
    REGISTRATION_VERIFY_PIN,
    REGISTRATION_COMPLETED,

    // Main questions
    MAIN_ENTER_PIN,
    MAIN_GENERAL,
    MAIN_RECORD_KEEPING,
    MAIN_MARKETPLACE,
    MAIN_BUY_AIRTIME,
    MAIN_MY_ACCOUNT,
    MAIN_HELP
}
